event_calendar:
    resource: "@EventCalendarBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

my_app:
    resource: "@EventCalendarBundle/Controller/"
    type:     annotation
